// <auto-generated />
using System;
using HaccpBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HaccpBackend.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20260419093427_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HaccpBackend.Domain.CheckItems.ActualCheckItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BasedOnCheckItemId")
                        .HasColumnType("integer")
                        .HasColumnName("based_on_check_item_id");

                    b.Property<int>("CheckItemType")
                        .HasColumnType("integer")
                        .HasColumnName("check_item_type");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.HasKey("Id")
                        .HasName("pk_actual_check_items");

                    b.HasIndex("BasedOnCheckItemId")
                        .HasDatabaseName("ix_actual_check_items_based_on_check_item_id");

                    b.ToTable("actual_check_items", (string)null);

                    b.HasDiscriminator<int>("CheckItemType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HaccpBackend.Domain.CheckItems.CheckItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckItemType")
                        .HasColumnType("integer")
                        .HasColumnName("check_item_type");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_check_items");

                    b.ToTable("check_items", (string)null);
                });

            modelBuilder.Entity("HaccpBackend.Domain.Logs.ActualLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BasedOnLogId")
                        .HasColumnType("integer")
                        .HasColumnName("based_on_log_id");

                    b.Property<TimeOnly>("CanBeFilledFrom")
                        .HasColumnType("time without time zone")
                        .HasColumnName("can_be_filled_from");

                    b.Property<int?>("CheckedById")
                        .HasColumnType("integer")
                        .HasColumnName("checked_by_id");

                    b.Property<DateTime?>("CheckedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_on");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_actual_logs");

                    b.HasIndex("BasedOnLogId")
                        .HasDatabaseName("ix_actual_logs_based_on_log_id");

                    b.HasIndex("CheckedById")
                        .HasDatabaseName("ix_actual_logs_checked_by_id");

                    b.ToTable("actual_logs", (string)null);
                });

            modelBuilder.Entity("HaccpBackend.Domain.Logs.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<TimeSpan>("TimeToFill")
                        .HasColumnType("interval")
                        .HasColumnName("time_to_fill");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("HaccpBackend.Domain.Organizations.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("HaccpBackend.Domain.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_users_organization_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HaccpBackend.Domain.Vendors.OpeningHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CloseAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("close_at");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<TimeOnly>("OpenAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("open_at");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_opening_hours");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_opening_hours_vendor_id");

                    b.ToTable("opening_hours", (string)null);
                });

            modelBuilder.Entity("HaccpBackend.Domain.Vendors.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.ToTable("vendors", (string)null);
                });

            modelBuilder.Entity("HaccpBackend.Domain.Vendors.VendorUserAccess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<bool>("IsPrimaryLocation")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary_location");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_vendor_user_accesses");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_vendor_user_accesses_user_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_vendor_user_accesses_vendor_id");

                    b.ToTable("vendor_user_accesses", (string)null);
                });

            modelBuilder.Entity("HaccpBackend.Domain.CheckItems.BooleanCheckItem", b =>
                {
                    b.HasBaseType("HaccpBackend.Domain.CheckItems.ActualCheckItem");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean")
                        .HasColumnName("value");

                    b.ToTable("actual_check_items", (string)null);

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("HaccpBackend.Domain.CheckItems.NumericCheckItem", b =>
                {
                    b.HasBaseType("HaccpBackend.Domain.CheckItems.ActualCheckItem");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.ToTable("actual_check_items", null, t =>
                        {
                            t.Property("Value")
                                .HasColumnName("numeric_check_item_value");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("HaccpBackend.Domain.CheckItems.TextCheckItem", b =>
                {
                    b.HasBaseType("HaccpBackend.Domain.CheckItems.ActualCheckItem");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.ToTable("actual_check_items", null, t =>
                        {
                            t.Property("Value")
                                .HasColumnName("text_check_item_value");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("HaccpBackend.Domain.CheckItems.ActualCheckItem", b =>
                {
                    b.HasOne("HaccpBackend.Domain.CheckItems.CheckItem", "BasedOnCheckItem")
                        .WithMany()
                        .HasForeignKey("BasedOnCheckItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_actual_check_items_check_items_based_on_check_item_id");

                    b.Navigation("BasedOnCheckItem");
                });

            modelBuilder.Entity("HaccpBackend.Domain.Logs.ActualLog", b =>
                {
                    b.HasOne("HaccpBackend.Domain.Logs.Log", "BasedOnLog")
                        .WithMany()
                        .HasForeignKey("BasedOnLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_actual_logs_logs_based_on_log_id");

                    b.HasOne("HaccpBackend.Domain.Users.User", "CheckedBy")
                        .WithMany()
                        .HasForeignKey("CheckedById")
                        .HasConstraintName("fk_actual_logs_users_checked_by_id");

                    b.Navigation("BasedOnLog");

                    b.Navigation("CheckedBy");
                });

            modelBuilder.Entity("HaccpBackend.Domain.Users.User", b =>
                {
                    b.HasOne("HaccpBackend.Domain.Organizations.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HaccpBackend.Domain.Vendors.OpeningHour", b =>
                {
                    b.HasOne("HaccpBackend.Domain.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_opening_hours_vendors_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("HaccpBackend.Domain.Vendors.VendorUserAccess", b =>
                {
                    b.HasOne("HaccpBackend.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_user_accesses_users_user_id");

                    b.HasOne("HaccpBackend.Domain.Vendors.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vendor_user_accesses_vendors_vendor_id");

                    b.Navigation("User");

                    b.Navigation("Vendor");
                });
#pragma warning restore 612, 618
        }
    }
}
